apiVersion: v1
baseDomain: example.com 
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones: []
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones: []
  replicas: 3
metadata:
  creationTimestamp: null
  name: your_clustername
networking:
  clusterNetwork:
  - cidr: 10.32.0.0/16
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: updateme
    subnets: []

pullSecret: "{ 'UpdateMe': true }"
sshKey: |
  ssh-rsa {{ yourkey }}
